---
- name: Add Docker GPG apt Key
  apt_key:
    url: "{{ UBUNTU_DOCKER_GPG_KEY_URL }}"
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb "{{ UBUNTU_DOCKER_REPO }}" "{{ UBUNTU_VERSION_CODE_NAME }}" stable
    state: present

- name: Make sure Docker engine is installed
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: true
    state: latest

- name: Install PIP packages
  pip:
    name:
      - docker
      - docker-compose

- name: Make sure Ubuntu user has proper access to docker group
  ansible.builtin.user:
    name: ubuntu
    shell: /bin/bash
    groups: docker
    append: true
  tags:
    - ubuntu_docker_group
